import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — LeadFlow CRM',
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16 prose prose-neutral dark:prose-invert">
      <Link href="/" className="text-sm text-muted-foreground no-underline hover:text-foreground">
        &larr; Home
      </Link>

      <h1 className="mt-4">Terms of Service</h1>
      <p className="text-sm text-muted-foreground">Last updated: May 12, 2026</p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using LeadFlow CRM (&quot;the Service&quot;), you agree to be bound by these
        Terms of Service. If you do not agree, do not use the Service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        LeadFlow CRM is a multi-tenant AI-powered sales CRM that provides lead management,
        pipeline tracking, AI research, CSV import, task management, deal tracking, and
        project management features.
      </p>

      <h2>3. Account Registration</h2>
      <ul>
        <li>You must provide accurate and complete registration information</li>
        <li>You are responsible for maintaining the security of your account credentials</li>
        <li>You must be at least 18 years old to use the Service</li>
        <li>One person or organization may not maintain multiple free accounts</li>
      </ul>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any illegal or unauthorized purpose</li>
        <li>Upload malicious files, spam content, or data that violates others&apos; privacy</li>
        <li>Attempt to bypass rate limits, security measures, or access controls</li>
        <li>Reverse engineer, decompile, or disassemble the Service</li>
        <li>Use the AI features to generate harmful, misleading, or abusive content</li>
        <li>Scrape or bulk-extract data from the Service</li>
      </ul>

      <h2>5. Data Ownership</h2>
      <p>
        You retain ownership of all data you upload to the Service (leads, contacts, notes, files).
        We do not claim ownership of your data. You grant us a limited license to process your
        data solely for providing the Service.
      </p>

      <h2>6. AI Features</h2>
      <ul>
        <li>AI research results are generated by third-party AI models and may contain inaccuracies</li>
        <li>AI features are subject to daily usage caps based on your plan</li>
        <li>You are responsible for verifying AI-generated insights before acting on them</li>
        <li>We are not liable for decisions made based on AI-generated content</li>
      </ul>

      <h2>7. Service Availability</h2>
      <p>
        We strive for high availability but do not guarantee uninterrupted service. We may
        perform scheduled maintenance with advance notice. We are not liable for downtime
        caused by factors beyond our control.
      </p>

      <h2>8. Payment & Plans</h2>
      <p>
        Free tier includes limited features and usage caps. Paid plans unlock additional
        features and higher limits. Billing terms are specified at the time of purchase.
        Refunds are handled on a case-by-case basis.
      </p>

      <h2>9. Termination</h2>
      <p>
        We may suspend or terminate your account if you violate these terms. You may delete
        your account at any time from Settings. Upon termination, your data will be deleted
        within 90 days.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        The Service is provided &quot;as is&quot; without warranties of any kind. We are not liable for
        any indirect, incidental, or consequential damages arising from your use of the Service.
        Our total liability is limited to the amount you paid us in the 12 months prior to the claim.
      </p>

      <h2>11. Changes to Terms</h2>
      <p>
        We may update these terms from time to time. Continued use of the Service after changes
        constitutes acceptance of the new terms.
      </p>

      <h2>12. Contact</h2>
      <p>
        For questions about these terms, contact us at{' '}
        <a href="mailto:legal@leadflow.app">legal@leadflow.app</a>.
      </p>
    </div>
  )
}
